version: "3.1"
services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Super
      MYSQL_DATABASE: wordleapi
    volumes:
      - ./initSQL:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"






