// Meter el cuerpo json en post y put

// Peticiones Game

### Obtener todos los juegos, no funciona
GET http://localhost:8080/api/games

### Obtener el juego con id 6, no funciona
GET http://localhost:8080/api/games/6


// Peticiones Matches

### No funciona
GET http://localhost:8080/api/matches

### No funciona
GET http://localhost:8080/api/matches/4

###
POST http://localhost:8080/api/matches

###
PUT http://localhost:8080/api/matches/5

### No funciona
DELETE http://localhost:8080/api/matches/6


// Peticiones Player

###
GET http://localhost:8080/api/players

###
GET http://localhost:8080/api/players/4

###
POST http://localhost:8080/api/players

###
PUT http://localhost:8080/api/players/8

### No funciona
DELETE http://localhost:8080/api/players/3


// Peticiones Team

###
GET http://localhost:8080/api/teams

###
GET http://localhost:8080/api/teams/4

###
POST http://localhost:8080/api/teams

###
PUT http://localhost:8080/api/teams/6

### No funciona
DELETE http://localhost:8080/api/teams/6


// Peticiones Word

### Obtener un número de palabras por defecto 10
GET http://localhost:8080/api/words?page=1&size=20

### Obtener toda la lista de palabras
GET http://localhost:8080/api/words/all

### Palabras que empiezan por antropo-
GET http://localhost:8080/api/words/starting/antropo

### Palabras que terminan en -ferro
GET http://localhost:8080/api/words/ending/ferro

### Palabras que contienen astr
GET http://localhost:8080/api/words/containing/astr

### Obtener una palabra aleatoria
GET http://localhost:8080/api/words/random

### Obtener un número específico de palabras aleatorias
GET http://localhost:8080/api/words/random/12