CREATE TABLE IF NOT EXISTS `wordleApi`.`Game` (
  `idGame` INT NOT NULL AUTO_INCREMENT,
  `Max_tries` INT NULL,
  `Description` VARCHAR(80) NULL,
  `Difficulty` ENUM('easy', 'normal', 'hard') NOT NULL,
  PRIMARY KEY (`idGame`)
    ) ENGINE = InnoDB;




INSERT INTO `wordleApi`.`Game` (
    `Max_tries`,
    `Description`,
    `Difficulty`
) VALUES
      (5, 'A simple game of guessing the five-letter word.', 'easy'),
      (6, 'A more challenging game with slightly more obscure words.', 'normal'),
      (7, 'The ultimate test of your vocabulary, with the hardest words of all.', 'hard'),
      (5, 'A game for children and beginners.', 'easy'),
      (6, 'A game for intermediate players.', 'normal'),
      (7, 'A game for advanced players.', 'hard'),
      (5, 'A game with words that are all related to a single theme.', 'easy'),
      (6, 'A game with words that are all related to a specific subject.', 'normal'),
      (7, 'A game with words that are all related to a specific place.', 'hard'),
      (5, 'A game with words that are all related to a specific time period.', 'easy'),
      (6, 'A game with words that are all related to a specific event.', 'normal'),
      (7, 'A game with words that are all related to a specific person.', 'hard'),
      (5, 'A game with words that are all related to a specific animal.', 'easy'),
      (6, 'A game with words that are all related to a specific plant.', 'normal'),
      (7, 'A game with words that are all related to a specific object.', 'hard'),
      (5, 'A game with words that are all related to a specific action.', 'easy'),
      (6, 'A game with words that are all related to a specific feeling.', 'normal'),
      (7, 'A game with words that are all related to a specific place.', 'hard'),
      (5, 'A game with words that are all related to a specific time period.', 'easy'),
      (6, 'A game with words that are all related to a specific event.', 'normal'),
      (7, 'A game with words that are all related to a specific person.', 'hard'),
      (5, 'A game with words that are all related to a specific animal.', 'easy'),
      (6, 'A game with words that are all related to a specific plant.', 'normal'),
      (7, 'A game with words that are all related to a specific object.', 'hard'),
      (5, 'A game with words that are all related to a specific action.', 'easy'),
      (6, 'A game with words that are all related to a specific feeling.', 'normal'),
      (7, 'A game with words that are all related to a specific place.', 'hard'),
      (5, 'A game with words that are all related to a specific time period.', 'easy'),
      (6, 'A game with words that are all related to a specific event.', 'normal'),
      (7, 'A game with words that are all related to a specific person.', 'hard'),
      (5, 'A game with words that are all related to a specific animal.', 'easy'),
      (6, 'A game with words that are all related to a specific plant.', 'normal'),
      (7, 'A game with words that are all related to a specific object.', 'hard'),
      (5, 'A game with words that are all related to a specific action.', 'easy'),
      (6, 'A game with words that are all related to a specific feeling.', 'normal'),
      (7, 'A game with words that are all related to a specific place.', 'hard'),
      (5, 'A game with words that are all related to a specific time period.', 'easy'),
      (6, 'A game with words that are all related to a specific event.', 'normal'),
      (7, 'A game with words that are all related to a specific person.', 'hard'),
      (5, 'A game with words that are all related to a specific animal.', 'easy'),
      (6, 'A game with words that are all related to a specific plant.', 'normal'),
      (7, 'A game with words that are all related to a specific object.', 'hard'),
      (5, 'A game with words that are all related to a specific action.', 'easy'),
      (6, 'A game with words that are all related to a specific feeling.', 'normal'),
      (7, 'A game with words that are all related to a specific place.', 'hard'),
      (5, 'A game with words that are all related to a specific time period.', 'easy'),
      (6, 'A game with words that are all related to a specific event.', 'normal'),
      (7, 'A game with words that are all related to a specific person.', 'hard'),
      (5, 'A game with words that are all related to a specific animal.', 'easy'),
      (6, 'A game with words that are all related to a specific plant.', 'normal'),
      (7, 'A game with words that are all related to a specific object.', 'hard'),
      (5, 'A game with words that are all related to a specific action.', 'easy'),
      (6, 'A game with words that are all related to a specific feeling.', 'normal'),
      (7, 'A game with words that are all related to a specific place.', 'hard'),
      (5, 'A game with words that are all related to a specific time period.', 'easy'),
      (6, 'A game with words that are all related to a specific event.', 'normal'),
      (7, 'A game with words that are all related to a specific person.', 'hard'),
      (5, 'A game with words that are all related to a specific animal.', 'easy'),
      (6, 'A game with words that are all related to a specific plant.', 'normal'),
      (7, 'A game with words that are all related to a specific object.', 'hard'),
      (5, 'A game with words that are all related to a specific action.', 'easy'),
      (6, 'A game with words that are all related to a specific feeling.', 'normal'),
      (7, 'A game with words that are all related to a specific place.', 'hard'),
      (5, 'A game with words that are all related to a specific time period.', 'easy'),
      (6, 'A game with words that are all related to a specific event.', 'normal'),
      (7, 'A game with words that are all related to a specific person.', 'hard'),
      (5, 'A game with words that are all related to a specific animal.', 'easy'),
      (6, 'A game with words that are all related to a specific plant.', 'normal'),
      (7, 'A game with words that are all related to a specific object.', 'hard'),
      (5, 'A game with words that are all related to a specific action.', 'easy'),
      (6, 'A game with words that are all related to a specific feeling.', 'normal'),
      (7, 'A game with words that are all related to a specific place.', 'hard');
